QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	-- Melee
--Kyros Weapon Pack V4
[`weapon_glock19x`] 	   = {['name'] = 'weapon_glock19x', 	    ['label'] = 'G19X XL', 	         ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL', 	 	      ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_glock19`] 		   = {['name'] = 'weapon_glock19', 	        ['label'] = 'GLOCK 19', 		 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	 	 	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_glock40`] 		   = {['name'] = 'weapon_glock40', 		    ['label'] = 'GLOCK 40', 		 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',   	 	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_glock40s`] 	   = {['name'] = 'weapon_glock40s', 	    ['label'] = 'GLOCK 40 SWITCH', 	 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	 	 	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_ddm4v5`] 	       = {['name'] = 'weapon_ddm4v5', 	        ['label'] = 'DDM4V5', 	         ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',    	 	  ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_mpx`] 	           = {['name'] = 'weapon_mpx', 	            ['label'] = 'MPX', 			     ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',    	 	  ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_pd509`] 		   = {['name'] = 'weapon_pd509', 		    ['label'] = 'PD 509', 	         ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',   	 	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_aps`]             = {['name'] = 'weapon_aps', 	            ['label'] = 'STECHKIN APS', 	 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',   	 	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_ppk`] 	           = {['name'] = 'weapon_ppk',              ['label'] = 'WALTHER PPK', 		 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',   	 	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_pitviper`]        = {['name'] = 'weapon_pitviper', 		['label'] = 'JW4 PIT VIPER',     ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',   	  	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_barp`] 	       = {['name'] = 'weapon_barp',             ['label'] = 'BANSHEE ARP-9', 	 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	 	  	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_rdp`] 	           = {['name'] = 'weapon_rdp', 	            ['label'] = 'BHELLCAT RDP', 	 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',		 	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_lok`] 	           = {['name'] = 'weapon_lok', 	            ['label'] = 'M-LOK AR 15', 		 ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',		 	  ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_plr`]   	       = {['name'] = 'weapon_plr', 	            ['label'] = 'PLR-16', 			 ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',		 	  ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_xds9`] 	       = {['name'] = 'weapon_xds9', 	        ['label'] = 'XDS9', 			 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	 	      ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_pps`]   	       = {['name'] = 'weapon_pps', 	            ['label'] = 'WALTHER PPS', 		 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	 		  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_xdme`] 	       = {['name'] = 'weapon_xdme', 	        ['label'] = 'XDM ELITE', 		 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	 	  	  ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_sp`]              = {['name'] = 'weapon_sp', 	            ['label'] = 'FN-15 PISTOL', 	 ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',	          ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_glock17s`]        = {['name'] = 'weapon_glock17s', 	    ['label'] = 'GLOCK 17 SWITCH',   ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	          ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_glock18c`] 	   = {['name'] = 'weapon_glock18c', 	    ['label'] = 'GLOCK 18C', 		 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	          ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_glock19s`] 	   = {['name'] = 'weapon_glock19s',         ['label'] = 'GLOCK 19 SWITCH', 	 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	          ['damagereason'] = 'Pistoled / Blasted / TANKED / Bust a cap in'},
[`weapon_arpistol`] 	   = {['name'] = 'weapon_arpistol',   	    ['label'] = 'TATIC ARP 9MM', 	 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',	          ['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
[`weapon_glock26s`]        = {['name'] = 'weapon_glock26s', 	    ['label'] = 'GLOCK 26 SWITCH', 	 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL',            ['damagereason'] = 'Ended / Sprayed / Shot down / Floored'},
[`weapon_grenades`]        = {['name'] = 'weapon_grenades', 	    ['label'] = 'GRENADE SNIPER', 	 ['weapontype'] = 'Heavy Weapons',   ['ammotype'] = 'AMMO_GRENADELAUNCHER',   ['damagereason'] = 'BOOM / BLAST / Blinded / FUCKED UP'},
[`weapon_m32s`] 		   = {['name'] = 'weapon_m32s', 	        ['label'] = 'M32 SMOKE GL', 	 ['weapontype'] = 'Heavy Weapons',   ['ammotype'] = 'AMMO_GRENADELAUNCHER',   ['damagereason'] = 'Smoked / Pulverized / Blinded'},
[`weapon_microdraco`] 	   = {['name'] = 'weapon_microdraco', 	    ['label'] = 'MICRO DRACO', 		 ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',             ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_ruger57`] 	       = {['name'] = 'weapon_ruger57', 		    ['label'] = 'RUGER 57', 		 ['weapontype'] = 'Pistol',          ['ammotype'] = 'AMMO_PISTOL', 	 	      ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_mk18`]            = {['name'] = 'weapon_mk18', 	        ['label'] = 'MK18 MOD 1', 		 ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',    	 	  ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
[`weapon_680`]             = {['name'] = 'weapon_680', 	            ['label'] = 'MODEL 680', 		 ['weapontype'] = 'Shotgun',         ['ammotype'] = 'AMMO_SHOTGUN',  	  	  ['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
[`weapon_ziptie`]          = {['name'] = 'weapon_ziptie', 	        ['label'] = 'ZIP TIE M4A1',      ['weapontype'] = 'Assault Rifle',   ['ammotype'] = 'AMMO_RIFLE',    	 	  ['damagereason'] = 'Ended / Rifled / Shot down / Floored'},



	[`weapon_sb4s`] 			     = {['name'] = 'weapon_sb4s', 		        ['label'] = 'SB-4S', 			            ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
    [`weapon_m133`] 		         = {['name'] = 'weapon_m133', 	 	        ['label'] = 'M-133', 			            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_neva`] 		         = {['name'] = 'weapon_neva', 	 	        ['label'] = 'NEVA', 			            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_iar`] 		             = {['name'] = 'weapon_iar', 	 	        ['label'] = 'Infantry AR', 			        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_famasu1`] 		         = {['name'] = 'weapon_famasu1', 	 	    ['label'] = 'Famas Underground', 			['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_grau`] 		         = {['name'] = 'weapon_grau', 	 	        ['label'] = 'Grau 5.56', 			        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_jrbak`] 		         = {['name'] = 'weapon_jrbak', 	 	        ['label'] = 'JRB-AK', 			            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ak47s`] 		         = {['name'] = 'weapon_ak47s', 	 	        ['label'] = 'AK-47S', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_a15rc`] 		         = {['name'] = 'weapon_a15rc', 	 	        ['label'] = 'A15 RC', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_sr47`] 		         = {['name'] = 'weapon_sr47', 	 	        ['label'] = 'SR-47', 			            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_casr`] 		         = {['name'] = 'weapon_casr', 	 	        ['label'] = 'CASR', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_drh`] 		             = {['name'] = 'weapon_drh', 	 	        ['label'] = 'DRH', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_fn42`] 		         = {['name'] = 'weapon_fn42', 	 	        ['label'] = 'FN-42', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m16a3`] 		         = {['name'] = 'weapon_m16a3', 	 	        ['label'] = 'M16A3', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_fmr`] 		             = {['name'] = 'weapon_fmr', 	 	        ['label'] = 'FMR', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_galilar`] 		         = {['name'] = 'weapon_galilar', 	 	    ['label'] = 'GALIL AR', 				    ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ak4k`] 		         = {['name'] = 'weapon_ak4k', 	 	        ['label'] = 'AK-4K', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_akmkh`] 		         = {['name'] = 'weapon_akmkh', 	 	        ['label'] = 'AKM-KH', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_slr15`] 		         = {['name'] = 'weapon_slr15', 	 	        ['label'] = 'SLR-15', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_bulldog`] 		         = {['name'] = 'weapon_bulldog', 	 	    ['label'] = 'BULLDOG', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_fn502`] 		         = {['name'] = 'weapon_fn502', 	 	        ['label'] = 'FN502', 				        ['weapontype'] = 'Pistol',	        ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
    [`weapon_sfak`] 		         = {['name'] = 'weapon_sfak', 	 	        ['label'] = 'SF-AK', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ars`] 		             = {['name'] = 'weapon_ars', 	 	        ['label'] = 'ARS', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_arc15`] 		         = {['name'] = 'weapon_arc15', 	 	        ['label'] = 'ARC15', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_safak`] 		         = {['name'] = 'weapon_safak', 	 	        ['label'] = 'SAFAK', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_howa_2`] 		         = {['name'] = 'weapon_howa_2', 	 	    ['label'] = 'HOWA v2', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mza`] 		             = {['name'] = 'weapon_mza', 	 	        ['label'] = 'MZA', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_sar`] 		             = {['name'] = 'weapon_sar', 	 	        ['label'] = 'SAR', 			                ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_hfsmg`] 			     = {['name'] = 'weapon_hfsmg', 		        ['label'] = 'HFSMG', 			            ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_h2smg`] 			     = {['name'] = 'weapon_h2smg', 		        ['label'] = 'H2SMG', 			            ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_arma1`] 		         = {['name'] = 'weapon_arma1', 	 	        ['label'] = 'ARMA1', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ue4`] 		             = {['name'] = 'weapon_ue4', 	 	        ['label'] = 'UE4', 				            ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',	    ['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_sfrifle`] 		         = {['name'] = 'weapon_sfrifle', 	 	    ['label'] = 'SF-RIFLE', 				    ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_sf2`] 		             = {['name'] = 'weapon_sf2', 	 	        ['label'] = 'SF-2', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_nanite`] 		         = {['name'] = 'weapon_nanite', 	 	    ['label'] = 'NANITE', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_g36`] 		             = {['name'] = 'weapon_g36', 	 	        ['label'] = 'G36', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_sarb`] 		         = {['name'] = 'weapon_sarb', 	 	        ['label'] = 'SARB', 				        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',	    ['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_lr300`] 		         = {['name'] = 'weapon_lr300', 	 	        ['label'] = 'LR300', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m416p`] 		         = {['name'] = 'weapon_m416p', 	 	        ['label'] = 'M416P', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ms32`] 		         = {['name'] = 'weapon_ms32', 	 	        ['label'] = 'MS32', 				        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',	    ['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_idw`] 		             = {['name'] = 'weapon_idw', 	 	        ['label'] = 'IDW', 				            ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',	    ['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_aug`] 		             = {['name'] = 'weapon_aug', 	 	        ['label'] = 'AUG', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_g3_2`] 		         = {['name'] = 'weapon_g3_2', 	 	        ['label'] = 'G3 v2', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_uzi`] 		             = {['name'] = 'weapon_uzi', 	 	        ['label'] = 'UZI', 				            ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',	    ['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_sunda`] 		         = {['name'] = 'weapon_sunda', 	 	        ['label'] = 'SUNDA', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_cfs`] 		             = {['name'] = 'weapon_cfs', 	 	        ['label'] = 'CFS', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_ak47`] 		         = {['name'] = 'weapon_ak47', 	 	        ['label'] = 'AK-47', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_awp`] 			         = {['name'] = 'weapon_awp', 	 	        ['label'] = 'AWP', 			                ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER',	['damagereason'] = 'Sniped / Picked off / Scoped'},
    [`weapon_groza`] 		         = {['name'] = 'weapon_groza', 	 	        ['label'] = 'GROZA', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_ditdg`] 			     = {['name'] = 'weapon_ditdg', 	 	        ['label'] = 'DITDG', 			            ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER',	['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_acr`] 		         	 = {['name'] = 'weapon_acr', 	 	        ['label'] = 'ACR', 				        	['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_tar21`] 		         = {['name'] = 'weapon_tar21', 	 	        ['label'] = 'TAR21', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_acwr`] 		         = {['name'] = 'weapon_acwr', 	 	        ['label'] = 'ACWR', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_anarchy`] 		         = {['name'] = 'weapon_anarchy', 	 	    ['label'] = 'ANARCHY', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_gk47`] 		         = {['name'] = 'weapon_gk47', 	 	        ['label'] = 'GK-47', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_far`] 		         	 = {['name'] = 'weapon_far', 	 	        ['label'] = 'FAR', 				       		['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_heavysmg`] 		     = {['name'] = 'weapon_heavysmg', 	 	    ['label'] = 'HEAVY SMG', 				    ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_gys`] 		         	 = {['name'] = 'weapon_gys', 	 	        ['label'] = 'GYS', 				        	['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_akpu`] 		         = {['name'] = 'weapon_akpu', 	 	        ['label'] = 'AKPU', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ump45`] 		         = {['name'] = 'weapon_ump45', 	 	        ['label'] = 'UMP-45', 				        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_m82`] 		         	 = {['name'] = 'weapon_m82', 	 	        ['label'] = 'M82', 				        	['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_sb181`] 		         = {['name'] = 'weapon_sb181', 	 	        ['label'] = 'SB181', 				        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_ss2_2`] 		         = {['name'] = 'weapon_ss2_2', 	 	        ['label'] = 'SS2 v2', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_art64`] 		         = {['name'] = 'weapon_art64', 	 	        ['label'] = 'AR-T64', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_hfap`] 		         = {['name'] = 'weapon_hfap', 	 	        ['label'] = 'HFAP', 				        ['weapontype'] = 'Pistol',			['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_sm237`] 		         = {['name'] = 'weapon_sm237', 	 	        ['label'] = 'SM-237', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_r99`] 		         	 = {['name'] = 'weapon_r99', 	 	        ['label'] = 'R99', 				        	['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_cz75`] 		         = {['name'] = 'weapon_cz75', 	 	        ['label'] = 'CZ75', 				        ['weapontype'] = 'Pistol',			['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_pl14`] 		         = {['name'] = 'weapon_pl14', 	 	        ['label'] = 'PL14', 				        ['weapontype'] = 'Pistol',			['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_va030`] 		         = {['name'] = 'weapon_va030', 	 	        ['label'] = 'VA030', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ar727`] 		         = {['name'] = 'weapon_ar727', 	 	        ['label'] = 'AR-727', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_scarsc`] 		         = {['name'] = 'weapon_scarsc', 	 	    ['label'] = 'SCARSC', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ar121`] 		         = {['name'] = 'weapon_ar121', 	 	        ['label'] = 'AR-121', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_smg1311`] 		         = {['name'] = 'weapon_smg1311', 	 	    ['label'] = 'SMG1311', 				        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_dcs`] 		         	 = {['name'] = 'weapon_dcs', 	 	        ['label'] = 'DCS', 				        	['weapontype'] = 'Shotgun',			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_anr15`] 		         = {['name'] = 'weapon_anr15', 	 	        ['label'] = 'ANR15', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_owshotgun`] 		     = {['name'] = 'weapon_owshotgun', 	 	    ['label'] = 'OWSHOTGUN', 				    ['weapontype'] = 'Shotgun',			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_highboot`] 	         = {['name'] = 'weapon_highboot', 			['label'] = 'HIGHBOOT', 					['weapontype'] = 'Throwable',		['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_anm4`] 		         = {['name'] = 'weapon_anm4', 	 	        ['label'] = 'ANM4', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_gvandal`] 		         = {['name'] = 'weapon_gvandal', 	 	    ['label'] = 'GVANDAL', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_limpid`] 		         = {['name'] = 'weapon_limpid', 	 	    ['label'] = 'LIMPID', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_akbg`] 		         = {['name'] = 'weapon_akbg', 	 	        ['label'] = 'AKBG', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_pasmg`] 		         = {['name'] = 'weapon_pasmg', 	 	        ['label'] = 'PASMG', 				        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_mx4`] 			         = {['name'] = 'weapon_mx4', 		        ['label'] = 'MX4', 			                ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_truvelo`] 		         = {['name'] = 'weapon_truvelo', 	 	    ['label'] = 'TRUVELO', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_autosmg`] 			     = {['name'] = 'weapon_autosmg', 		    ['label'] = 'AUTOSMG', 			            ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_benellim4`] 		     = {['name'] = 'weapon_benellim4', 	 	    ['label'] = 'BENELLIM4', 				    ['weapontype'] = 'Shotgun',	        ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_l85`] 		             = {['name'] = 'weapon_l85', 	 	        ['label'] = 'L85', 				            ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_book`] 	             = {['name'] = 'weapon_book', 			    ['label'] = 'BOOK', 					    ['weapontype'] = 'Throwable',		['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_brick`] 	             = {['name'] = 'weapon_brick', 			    ['label'] = 'BRICK', 					    ['weapontype'] = 'Throwable',		['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_dks501`] 		         = {['name'] = 'weapon_dks501', 	 	    ['label'] = 'DKS501', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_energyknife`] 			 = {['name'] = 'weapon_energyknife', 	    ['label'] = 'Energy Knife', 				['weapontype'] = 'Melee',	        ['ammotype'] = nil,	            ['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_karambit`] 			 = {['name'] = 'weapon_karambit', 			['label'] = 'Karambit', 				    ['weapontype'] = 'Melee',	        ['ammotype'] = nil,	            ['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_scifw`] 		         = {['name'] = 'weapon_scifw', 	 	        ['label'] = 'SCIFW', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ssr56`] 		         = {['name'] = 'weapon_ssr56', 	 	        ['label'] = 'SSR56', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_lgwii`] 		         = {['name'] = 'weapon_lgwii', 	 	        ['label'] = 'Lewis Gun WWII', 				['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m90s`] 		         = {['name'] = 'weapon_m90s', 	 	        ['label'] = 'M90S', 				        ['weapontype'] = 'Shotgun',	        ['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_an94_2`] 		         = {['name'] = 'weapon_an94_2', 	 	    ['label'] = 'AN94_2', 				        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_smg9`] 		         = {['name'] = 'weapon_smg9', 	 	        ['label'] = 'SMG9', 				        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG',	    ['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_knr`] 		             = {['name'] = 'weapon_knr', 	 	        ['label'] = 'KNR', 				            ['weapontype'] = 'Pistol',	        ['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},


		-- Custom Weapons
		
	[`weapon_m70`] 		 = {['name'] = 'weapon_m70', 	 	['label'] = 'M70', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_de`] 			 = {['name'] = 'weapon_de', 		['label'] = 'Desert Eagle', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_fnx45`] 			 = {['name'] = 'weapon_fnx45', 		['label'] = 'FN FNX45', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_glock17`] 			 = {['name'] = 'weapon_glock17', 		['label'] = 'PD Glock 17', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_m4`] 		 = {['name'] = 'weapon_m4', 	 	['label'] = 'PD M4A1', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m9`] 			 = {['name'] = 'weapon_m9', 		['label'] = 'Beretta M9A3', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_m1911`] 			 = {['name'] = 'weapon_m1911', 		['label'] = 'M1911', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	
	[`weapon_mac10`] 			 = {['name'] = 'weapon_mac10', 		['label'] = 'MAC-10', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_mossberg`] 		 = {['name'] = 'weapon_mossberg', 	['label'] = 'Mossberg 500', 		['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_remington`] 		 = {['name'] = 'weapon_remington', 	['label'] = 'Remington 870', 		['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_scarh`] 		 = {['name'] = 'weapon_scarh', 	['label'] = 'PD SCAR-H', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_shiv`] 				 = {['name'] = 'weapon_shiv', 			['label'] = 'Shiv', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_katana`] 				 = {['name'] = 'weapon_katana', 			['label'] = 'Katana', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_sledgehammer`] 				 = {['name'] = 'weapon_sledgehammer', 			['label'] = 'Sledge Hammer', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
        [`weapon_ar15`] 		 = {['name'] = 'weapon_ar15', 	 	['label'] = 'PD AR-15', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mk14`] 		 = {['name'] = 'weapon_mk14', 	 	['label'] = 'PD MK14', 				['ammotype'] = 'AMMO_SNIPER',	['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
	[`weapon_huntingrifle`] 		 = {['name'] = 'weapon_huntingrifle', 	 	['label'] = 'Hunting Rifle', 				['ammotype'] = 'AMMO_SNIPER',	['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
	[`weapon_mp9`] 			 = {['name'] = 'weapon_mp9', 		['label'] = 'MP9', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_m110`] 		 = {['name'] = 'weapon_m110', 	 	['label'] = 'M110', 				['ammotype'] = 'AMMO_SNIPER',	['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
	[`weapon_hk416`] 		 = {['name'] = 'weapon_hk416', 	 	['label'] = 'HK-416', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ak74`] 		 = {['name'] = 'weapon_ak74', 	 	    ['label'] = 'AK-74', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_aks74`] 		 = {['name'] = 'weapon_aks74', 	 	    ['label'] = 'AK-S74', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_glock22`] 		 = {['name'] = 'weapon_glock22', 		['label'] = 'Glock 22', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_glock18c`] 	 = {['name'] = 'weapon_glock18c', 		['label'] = 'Glock 18C', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_mp5`] 			 = {['name'] = 'weapon_mp5', 		    ['label'] = 'H&K MP5', 				['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_colbaton`] 	 = {['name'] = 'weapon_colbaton', 		['label'] = 'Baton', 				['ammotype'] = nil,	            ['damagereason'] = 'Beat'},

	[`weapon_unarmed`] 				 = {['name'] = 'weapon_unarmed', 		['label'] = 'Fists', 				['ammotype'] = nil, ['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_dagger`] 				 = {['name'] = 'weapon_dagger', 		['label'] = 'Dagger', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_bat`] 					 = {['name'] = 'weapon_bat', 			['label'] = 'Bat', 					['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_bottle`] 				 = {['name'] = 'weapon_bottle', 		['label'] = 'Broken Bottle', 		['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_crowbar`] 				 = {['name'] = 'weapon_crowbar', 		['label'] = 'Crowbar', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_flashlight`] 			 = {['name'] = 'weapon_flashlight', 	['label'] = 'Flashlight', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_golfclub`] 			 = {['name'] = 'weapon_golfclub', 		['label'] = 'Golfclub', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_hammer`] 				 = {['name'] = 'weapon_hammer', 		['label'] = 'Hammer', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_hatchet`] 				 = {['name'] = 'weapon_hatchet', 		['label'] = 'Hatchet', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_knuckle`] 				 = {['name'] = 'weapon_knuckle', 		['label'] = 'Knuckle', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_knife`] 				 = {['name'] = 'weapon_knife', 			['label'] = 'Knife', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_machete`] 				 = {['name'] = 'weapon_machete', 		['label'] = 'Machete', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_switchblade`] 			 = {['name'] = 'weapon_switchblade', 	['label'] = 'Switchblade', 			['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_nightstick`] 			 = {['name'] = 'weapon_nightstick', 	['label'] = 'Nightstick', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_wrench`] 				 = {['name'] = 'weapon_wrench', 		['label'] = 'Wrench', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_battleaxe`] 			 = {['name'] = 'weapon_battleaxe', 		['label'] = 'Battle Axe', 			['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_poolcue`] 				 = {['name'] = 'weapon_poolcue', 		['label'] = 'Poolcue', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_briefcase`] 			 = {['name'] = 'weapon_briefcase', 		['label'] = 'Briefcase', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_briefcase_02`] 		 = {['name'] = 'weapon_briefcase_02', 	['label'] = 'Briefcase', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_garbagebag`] 			 = {['name'] = 'weapon_garbagebag', 	['label'] = 'Garbage Bag', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_handcuffs`] 			 = {['name'] = 'weapon_handcuffs', 		['label'] = 'Handcuffs', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_bread`] 				 = {['name'] = 'weapon_bread', 			['label'] = 'Baquette', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_stone_hatchet`] 		 = {['name'] = 'weapon_stone_hatchet', 	['label'] = 'Weapon Stone Hatchet', ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},

    -- Handguns
	[`weapon_pistol`] 				 = {['name'] = 'weapon_pistol', 		['label'] = 'Walther P99', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_pistol_mk2`] 			 = {['name'] = 'weapon_pistol_mk2', 	['label'] = 'Pistol Mk II', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_combatpistol`] 		 = {['name'] = 'weapon_combatpistol', 	['label'] = 'Combat Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_appistol`] 			 = {['name'] = 'weapon_appistol', 		['label'] = 'AP Pistol', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_stungun`] 				 = {['name'] = 'weapon_stungun', 		['label'] = 'Taser', 					['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Died'},
	[`weapon_pistol50`] 			 = {['name'] = 'weapon_pistol50', 		['label'] = 'Pistol .50 Cal', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_snspistol`] 			 = {['name'] = 'weapon_snspistol', 		['label'] = 'SNS Pistol', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_snspistol_mk2`] 	     = {['name'] = 'weapon_snspistol_mk2', 	['label'] = 'SNS Pistol MK2', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_heavypistol`] 			 = {['name'] = 'weapon_heavypistol', 	['label'] = 'Heavy Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_vintagepistol`] 		 = {['name'] = 'weapon_vintagepistol', 	['label'] = 'Vintage Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_flaregun`] 			 = {['name'] = 'weapon_flaregun', 		['label'] = 'Flare Gun', 				['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Died'},
	[`weapon_marksmanpistol`] 		 = {['name'] = 'weapon_marksmanpistol', ['label'] = 'Marksman Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_revolver`] 			 = {['name'] = 'weapon_revolver', 		['label'] = 'Revolver', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_revolver_mk2`] 		 = {['name'] = 'weapon_revolver_mk2', 	['label'] = 'Violence', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_doubleaction`] 	     = {['name'] = 'weapon_doubleaction', 	['label'] = 'Double Action Revolver',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_raypistol`]			 = {['name'] = 'weapon_raypistol',		['label'] = 'Weapon Raypistol',			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_ceramicpistol`]		 = {['name'] = 'weapon_ceramicpistol', 	['label'] = 'Weapon Ceramicpistol',		['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_navyrevolver`]        	 = {['name'] = 'weapon_navyrevolver', 	['label'] = 'Weapon Navyrevolver',		['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_gadgetpistol`] 		 = {['name'] = 'weapon_gadgetpistol', 	['label'] = 'Weapon Gadgetpistol',		['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_stungun_mp`] 			 = {['name'] = 'weapon_stungun_mp', 	['label'] = 'Taser', 					['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Died'},
	[`WT_PLASMAP`] 				 = {['name'] = 'WT_PLASMAP', 		['label'] = 'plasma', 					['ammotype'] = 'AMMO_PLASMAP',	['damagereason'] = 'nill'},
	
    -- Submachine Guns
	[`weapon_microsmg`] 			 = {['name'] = 'weapon_microsmg', 		['label'] = 'Micro SMG', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_smg`] 				 	 = {['name'] = 'weapon_smg', 			['label'] = 'SMG', 					['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_smg_mk2`] 				 = {['name'] = 'weapon_smg_mk2', 		['label'] = 'PD MP5 2', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_assaultsmg`] 			 = {['name'] = 'weapon_assaultsmg', 	['label'] = 'Assault SMG', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_combatpdw`] 			 = {['name'] = 'weapon_combatpdw', 		['label'] = 'Combat PDW', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_machinepistol`] 		 = {['name'] = 'weapon_machinepistol', 	['label'] = 'Tec-9', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_minismg`] 				 = {['name'] = 'weapon_minismg', 		['label'] = 'Mini SMG', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_raycarbine`]	         = {['name'] = 'weapon_raycarbine', 	['label'] = 'Weapon Raycarbine',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},

    -- Shotguns
	[`weapon_pumpshotgun`] 			 = {['name'] = 'weapon_pumpshotgun', 	 	['label'] = 'Pump Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_pumpshotgun_mk2`]		 = {['name'] = 'weapon_pumpshotgun_mk2',	['label'] = 'Pumpshotgun MK2', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_sawnoffshotgun`] 		 = {['name'] = 'weapon_sawnoffshotgun', 	['label'] = 'Sawn-off Shotgun', 		['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_assaultshotgun`] 		 = {['name'] = 'weapon_assaultshotgun', 	['label'] = 'Assault Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_bullpupshotgun`] 		 = {['name'] = 'weapon_bullpupshotgun', 	['label'] = 'Bullpup Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_musket`] 			     = {['name'] = 'weapon_musket', 			['label'] = 'Musket', 					['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_heavyshotgun`] 		 = {['name'] = 'weapon_heavyshotgun', 	 	['label'] = 'Heavy Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_dbshotgun`] 			 = {['name'] = 'weapon_dbshotgun', 		 	['label'] = 'Double-barrel Shotgun', 	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_autoshotgun`] 			 = {['name'] = 'weapon_autoshotgun', 	 	['label'] = 'Auto Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_combatshotgun`]		 = {['name'] = 'weapon_combatshotgun', 		['label'] = 'Weapon Combatshotgun',		['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},

    -- Assault Rifles
	[`weapon_assaultrifle`] 		 = {['name'] = 'weapon_assaultrifle', 	 	['label'] = 'Assault Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_assaultrifle_mk2`] 	 = {['name'] = 'weapon_assaultrifle_mk2', 	['label'] = 'AK-47 MK2', 					['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_carbinerifle`] 		 = {['name'] = 'weapon_carbinerifle', 	 	['label'] = 'Carbine Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_carbinerifle_mk2`] 	 = {['name'] = 'weapon_carbinerifle_mk2', 	['label'] = 'PD 762', 						['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_advancedrifle`] 		 = {['name'] = 'weapon_advancedrifle', 	 	['label'] = 'Advanced Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_specialcarbine`] 		 = {['name'] = 'weapon_specialcarbine', 	['label'] = 'Special Carbine', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_specialcarbine_mk2`]	 = {['name'] = 'weapon_specialcarbine_mk2',	['label'] = 'Weapon Wpecialcarbine MK2',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_bullpuprifle`] 		 = {['name'] = 'weapon_bullpuprifle', 	 	['label'] = 'Bullpup Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_bullpuprifle_mk2`]		 = {['name'] = 'weapon_bullpuprifle_mk2', 	['label'] = 'Bull Puprifle MK2',			['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_compactrifle`] 		 = {['name'] = 'weapon_compactrifle', 	 	['label'] = 'Compact Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_militaryrifle`]		 = {['name'] = 'weapon_militaryrifle', 		['label'] = 'Weapon Militaryrifle',			['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_heavyrifle`] 			 = {['name'] = 'weapon_heavyrifle', 	 	['label'] = 'Heavy Rifle', 					['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},

    -- Light Machine Guns
	[`weapon_mg`] 					 = {['name'] = 'weapon_mg', 			['label'] = 'Machinegun', 			['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_combatmg`] 			 = {['name'] = 'weapon_combatmg', 		['label'] = 'Combat MG', 			['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_combatmg_mk2`]	 		 = {['name'] = 'weapon_combatmg_mk2', 	['label'] = 'Weapon Combatmg MK2',	['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_gusenberg`] 			 = {['name'] = 'weapon_gusenberg', 		['label'] = 'Thompson SMG', 		['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},

    -- Sniper Rifles
	[`weapon_sniperrifle`] 			 = {['name'] = 'weapon_sniperrifle', 	 	['label'] = 'Sniper Rifle', 			['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_heavysniper`] 			 = {['name'] = 'weapon_heavysniper', 	 	['label'] = 'Heavy Sniper', 			['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_heavysniper_mk2`]		 = {['name'] = 'weapon_heavysniper_mk2', 	['label'] = 'Weapon Heavysniper MK2',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_marksmanrifle`] 		 = {['name'] = 'weapon_marksmanrifle', 	 	['label'] = 'Marksman Rifle', 			['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_marksmanrifle_mk2`]	 = {['name'] = 'weapon_marksmanrifle_mk2',	['label'] = 'Weapon Marksmanrifle MK2',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_remotesniper`] 		 = {['name'] = 'weapon_remotesniper', 	 	['label'] = 'Remote Sniper', 			['ammotype'] = 'AMMO_SNIPER_REMOTE',	['damagereason'] = 'Sniped / Picked off / Scoped'},

    -- Heavy Weapons
	[`weapon_rpg`] 					 = {['name'] = 'weapon_rpg', 			      	['label'] = 'RPG', 						['ammotype'] = 'AMMO_RPG',				['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_grenadelauncher`] 		 = {['name'] = 'weapon_grenadelauncher', 	  	['label'] = 'Grenade Launcher', 		['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_grenadelauncher_smoke`] = {['name'] = 'weapon_grenadelauncher_smoke',	['label'] = 'Smoke Grenade Launcher',	['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_minigun`] 				 = {['name'] = 'weapon_minigun', 		      	['label'] = 'Minigun', 					['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_firework`] 			 = {['name'] = 'weapon_firework', 		 	  	['label'] = 'Firework Launcher', 		['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_railgun`] 				 = {['name'] = 'weapon_railgun', 		 	  	['label'] = 'Railgun', 					['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_hominglauncher`] 		 = {['name'] = 'weapon_hominglauncher', 	 	['label'] = 'Homing Launcher', 			['ammotype'] = 'AMMO_STINGER',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_compactlauncher`] 		 = {['name'] = 'weapon_compactlauncher',  	  	['label'] = 'Compact Launcher', 		['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_rayminigun`]			 = {['name'] = 'weapon_rayminigun', 		 	['label'] = 'Weapon Rayminigun',		['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
    [`weapon_emplauncher`] 			 = {['name'] = 'weapon_emplauncher', 			['label'] = 'EMP Launcher', 			['ammotype'] = 'AMMO_EMPLAUNCHER',		['damagereason'] = 'Died'},

    -- Throwables
	[`weapon_grenade`] 		 = {['name'] = 'weapon_grenade', 		['label'] = 'Grenade', 			['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_bzgas`] 		 = {['name'] = 'weapon_bzgas', 			['label'] = 'BZ Gas', 			['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_molotov`] 		 = {['name'] = 'weapon_molotov', 		['label'] = 'Molotov', 			['ammotype'] = nil,				['damagereason'] = 'Torched / Flambeed / Barbecued'},
	[`weapon_stickybomb`] 	 = {['name'] = 'weapon_stickybomb', 	['label'] = 'C4', 				['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_proxmine`] 	 = {['name'] = 'weapon_proxmine', 		['label'] = 'Proxmine Grenade', ['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_snowball`] 	 = {['name'] = 'weapon_snowball', 		['label'] = 'Snowball', 		['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_pipebomb`] 	 = {['name'] = 'weapon_pipebomb', 		['label'] = 'Pipe Bomb', 		['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_ball`] 		 = {['name'] = 'weapon_ball', 			['label'] = 'Ball', 			['ammotype'] = 'AMMO_BALL',		['damagereason'] = 'Died'},
	[`weapon_smokegrenade`]  = {['name'] = 'weapon_smokegrenade', 	['label'] = 'Smoke Grenade', 	['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_flare`] 		 = {['name'] = 'weapon_flare', 			['label'] = 'Flare pistol', 	['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Died'},

    -- Miscellaneous
	[`weapon_petrolcan`] 			= {['name'] = 'weapon_petrolcan', 		 	['label'] = 'Petrol Can', 				['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
	[`gadget_parachute`] 			= {['name'] = 'gadget_parachute', 		 	['label'] = 'Parachute', 				['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_fireextinguisher`] 	= {['name'] = 'weapon_fireextinguisher',	['label'] = 'Fire Extinguisher',		['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_hazardcan`]			= {['name'] = 'weapon_hazardcan',			['label'] = 'Weapon Hazardcan',			['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
    [`weapon_fertilizercan`]		= {['name'] = 'weapon_fertilizercan',		['label'] = 'Fertilizer Can',			['ammotype'] = 'AMMO_FERTILIZERCAN',	['damagereason'] = 'Died'},
	[`weapon_barbed_wire`]			= {['name'] = 'weapon_barbed_wire',			['label'] = 'Barbed Wire',				['ammotype'] = nil,						['damagereason'] = 'Prodded'},
	[`weapon_drowning`]				= {['name'] = 'weapon_drowning',			['label'] = 'Drowning',					['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_drowning_in_vehicle`]	= {['name'] = 'weapon_drowning_in_vehicle',	['label'] = 'Drowning in a Vehicle',	['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_bleeding`]				= {['name'] = 'weapon_bleeding',			['label'] = 'Bleeding',					['ammotype'] = nil,						['damagereason'] = 'Bled out'},
	[`weapon_electric_fence`]		= {['name'] = 'weapon_electric_fence',		['label'] = 'Electric Fence',			['ammotype'] = nil,						['damagereason'] = 'Fried'},
	[`weapon_explosion`]			= {['name'] = 'weapon_explosion',			['label'] = 'Explosion',				['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_fall`]					= {['name'] = 'weapon_fall',				['label'] = 'Fall',						['ammotype'] = nil,						['damagereason'] = 'Committed suicide'},
	[`weapon_exhaustion`]			= {['name'] = 'weapon_exhaustion',			['label'] = 'Exhaustion',				['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_hit_by_water_cannon`]	= {['name'] = 'weapon_hit_by_water_cannon',	['label'] = 'Water Cannon',				['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_rammed_by_car`]		= {['name'] = 'weapon_rammed_by_car',		['label'] = 'Rammed - Vehicle',			['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[`weapon_run_over_by_car`]		= {['name'] = 'weapon_run_over_by_car',		['label'] = 'Run Over - Vehicle',		['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[`weapon_heli_crash`]			= {['name'] = 'weapon_heli_crash',			['label'] = 'Heli Crash',				['ammotype'] = nil,						['damagereason'] = 'Helicopter Crash'},
	[`weapon_fire`]					= {['name'] = 'weapon_fire',				['label'] = 'Fire',						['ammotype'] = nil,						['damagereason'] = 'Torched / Flambeed / Barbecued'},

	-- Animals
	[`weapon_animal`]	= {['name'] = 'weapon_animal',	['label'] = 'Animal',	['ammotype'] = nil,	['damagereason'] = 'Mauled'},
    [`weapon_cougar`]	= {['name'] = 'weapon_cougar',	['label'] = 'Cougar',	['ammotype'] = nil,	['damagereason'] = 'Mauled'},
}
